services:
  verbex-server:
    image: jchristn77/verbex-server:v0.1.0
    container_name: verbex-server
    ports:
      - "8080:8080"
    volumes:
      - ./server/verbex.json:/app/verbex.json
      - ./server/db/:/app/db/
      - ./server/data/:/app/data/
      - ./server/logs/:/app/logs/
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  verbex-dashboard:
    image: jchristn77/verbex-dashboard:v0.1.0
    container_name: verbex-dashboard
    ports:
      - "8200:8200"
    volumes:
      - ./dashboard/logs:/app/logs
    environment:
      - VERBEX_SERVER_URL=http://verbex-server:8080
    restart: unless-stopped
